[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
clan_program = "2GVYqx8UJQLD32m1ntHh8atTTu4itJFRmqazxWpJx2tg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
